apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jaylabs
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: jaylabs
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 150
