apiVersion: v1
kind: Pod
metadata:
  name: volume-mount
spec:
  containers:
  - name: volume-mount
    image: centos
    volumeMounts:
    - mountPath: /data/volume1
      name: volume1
    - mountPath: /data/volume2
      name: volume2
    args:
    - sleep
    - "1000000"
  volumes:
  - name: volume1
    nfs:
      path: /
      server: fs-123abc456.efs.us-east-1.amazonaws.com
  - name: volume2
    nfs:
      path: /
      server: fs-789abc101.efs.us-east-1.amazonaws.com
